### PR TITLE
Added P-384 Utils

### PR DESCRIPTION
**Pull request by overheadhunter**
Added some utility classes to generate P-384 key pairs, store them to PKCS12 files and load them again.

### CODE REVIEW

**Comment by overheadhunter** [comment]
@SailReal Can you verify if these changes work on Android 7?

```java
Path somePath = ...
P384KeyPair orig = P384KeyPair.generate();
orig.store(somePath, "somePassword".toCharArray());
P384KeyPair loaded = P384KeyPair.load(somePath, "somePassword".toCharArray());
assert orig.equals(loaded);
```

**Review by SailReal — CHANGES_REQUESTED** [review]
Looks very promising but [java.nio.file](https://developer.android.com/reference/java/nio/file/package-summary?hl=en) was added in API level 26 (Android 8.0) that means it is not possible to instantiate e.g. the `Path` class in pre Android 8.0 and pass it to `P384KeyPair`. Maybe we can provide further methods where we can pass in the input/output-stream of the key material like in `MasterkeyFileAccess`?

**Comment by overheadhunter** [comment]
> it is not possible to get e.g. a `Path` instance in pre Android 8.0 and pass it to `P384KeyPair`.

But it is still possible to load a class that has a `Path` in some unused method?

So overloading the method such as here works?

https://github.com/cryptomator/cryptolib/blob/3347bc0ffba91f5fda2919d4b1bfb6ad62c4f6d7/src/main/java/org/cryptomator/cryptolib/common/MasterkeyFileAccess.java#L117-L134

**Comment by SailReal** [comment]
> But it is still possible to load a class that has a Path in some unused method?
> 
> So overloading the method such as here works?

Yes to both questions :)

**Review by SailReal — APPROVED** [review]
LGTM, tested on Android 7 and 11:
```kotlin
val out = applicationContext.openFileOutput("foo", Context.MODE_PRIVATE)

val orig = P384KeyPair.generate();
orig.store(out, "somePassword".toCharArray())

val in = applicationContext.openFileInput("foo")

val loaded = P384KeyPair.load(in, "somePassword".toCharArray())

=> orig.equals(loaded)) == true
```

**Pull request merged**
